version: "3.8"
services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile.lab
    container_name: jupyterlab
    ports:
      - "9696:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ../library/:/data/
    environment:
      JUPYTER_ENABLE_LAB: "yes"

  deckard:
    build:
      context: ../magic/deckard
      dockerfile: Dockerfile
    container_name: deckard
    ports:
      - "9697:3000"
    volumes:
      - ../magic/deckard:/app
      - ../library/:/data/

      

