version: "3.8"
services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile.lab
    container_name: jupyterlab
    ports:
      - "9696:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ../library/:/data/
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      

